# Generated by Django 4.2.5 on 2023-11-01 21:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[accounts.models.validate_profanity],
            ),
        ),
    ]
