# Generated by Django 4.2.5 on 2023-11-02 16:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=30, validators=[accounts.models.validate_profanity]
            ),
        ),
    ]
