version: '3'

services:
  backend:
    build: ./todoqueue_backend
    command: ["gunicorn", "todoqueue_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./todoqueue_backend:/usr/src/app
      - static_volume:/usr/src/app/static
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=todoqueue
      - DJANGO_DB_USER=todoqueue
      - DJANGO_DB_PASSWORD=todoqueue

  nginx:
    image: nginx:1.19-alpine
    ports:
      - "3936:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/app/static
      - frontend_static:/usr/src/app/frontend
    depends_on:
      - backend
      - frontend

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoqueue
      MYSQL_USER: todoqueue
      MYSQL_PASSWORD: todoqueue
    volumes:
      - mariadb_data:/var/lib/mysql

  frontend:
    build: ./todoqueue-frontend
    volumes:
      - frontend_static:/usr/src/app/build
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3936/api/
    command: ["npm", "run", "build"]


volumes:
  mariadb_data:
  static_volume:
  frontend_static: