# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev default-libmysqlclient-dev pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the project files into the container
COPY . .

# Install project dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Collect static files
RUN python manage.py collectstatic --noinput

# Run the command to start the Django app
CMD ["gunicorn", "todoqueue_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
