# Generated by Django 4.2.5 on 2023-09-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_worklog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='task_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
