# Generated by Django 4.2.5 on 2023-09-18 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_worklog_task_json_alter_worklog_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tasks', models.ManyToManyField(related_name='households', to='tasks.task')),
                ('users', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
