# Generated by Django 4.2.5 on 2023-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_oneshottask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneshottask',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
